#!/bin/bash
# Author: Nikolaos Dimopoulos
# Based on code by Remigijus Jarmalavičius
# Checks the files to be committed for the presence of print_r(), var_dump() and die()
# The array below can be extended for further checks

checks[1]="var_dump("
checks[2]="print_r("
checks[3]="die"
element_count=${#checks[@]}
let "element_count = $element_count + 1"

ROOT_DIR="$(pwd)/"
LIST=$(git diff --cached --name-only --diff-filter=ACM)
ERRORS_BUFFER=""
for file in $LIST
do
    index=1
    while [ "$index" -lt "$element_count" ]
    do
        echo "Checking file: $file [${checks[$index]}]"
        ERRORS=$(grep "${checks[$index]}" $ROOT_DIR$file)
        if [ "$ERRORS" != "" ]; then
            mes="$file includes \"${checks[$index]}\""
            if [ "$ERRORS_BUFFER" != "" ]; then
                ERRORS_BUFFER="$ERRORS_BUFFER\n$mes\n"
            else
                ERRORS_BUFFER="$mes"
            fi
            echo "${checks[$index]} found in file: $file "
        fi
        let "index = $index + 1"
    done
done

if [ "$ERRORS_BUFFER" != "" ]; then
    echo 
    echo "These errors were found in try-to-commit files: "
    echo -e $ERRORS_BUFFER
    echo 
    echo "Can't commit, fix errors first."
    exit 1
else
    echo "Commited successfully."
fi
